\documentclass[11pt,english,dvipsnames,aspectratio=169,handout]{beamer}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{fontspec}
\setsansfont[Mapping=tex-text]{Fira Sans}
\setcounter{secnumdepth}{4}
\setcounter{tocdepth}{4}
\usepackage[normalem]{ulem}
\usepackage[T1]{fontenc}
\usepackage{dcolumn}
\usepackage{booktabs}
\usepackage{bm}
\usepackage{setspace}
\makeatletter
\usetheme{metropolis}
\setbeamertemplate{frame footer}{Bosancianu | Schaub | Hertie School}
\setbeamerfont{page number in head/foot}{size=\tiny}
\setbeamercolor{footline}{fg=gray}
\usepackage{xcolor}
\setbeamercovered{dynamic}
\usepackage{tikz, tikz-cd, animate}
\usetikzlibrary{arrows, positioning, fit, shapes.misc, shapes, backgrounds, trees}
\usetikzlibrary{decorations.pathreplacing}
\usepackage{pgfplots}
\pgfplotsset{compat=1.10}
\usepgfplotslibrary{fillbetween}
\usepackage{pgfplotstable}
\usepackage[labelformat=empty]{caption}
% For table captions in Beamer
\usepackage[sectionbib]{apacite}
\renewcommand{\bibliographytypesize}{\footnotesize}
\makeatletter
\let\st@rtbibsection\@bibnewpage
\let\st@rtbibchapter\@bibnewpage
\makeatother
\usepackage{amsmath, mathtools}
\usepackage{xunicode}
\usepackage{hyperref}
\usepackage{pgfplots}
\makeatletter
\long\def\ifnodedefined#1#2#3{%
    \@ifundefined{pgf@sh@ns@#1}{#3}{#2}%
}
\pgfplotsset{
    discontinuous/.style={
    scatter,
    scatter/@pre marker code/.code={
        \ifnodedefined{marker}{
            \pgfpointdiff{\pgfpointanchor{marker}{center}}%
             {\pgfpoint{0}{0}}%
             \ifdim\pgf@y>0pt
                \tikzset{options/.style={mark=*}}
                \draw [densely dashed] (marker-|0,0) -- (0,0);
                \draw plot [mark=*,mark options={fill=white}] coordinates {(marker-|0,0)};
             \else
                \ifdim\pgf@y<0pt
                    \tikzset{options/.style={mark=*,fill=white}}
                    \draw [densely dashed] (marker-|0,0) -- (0,0);
                    \draw plot [mark=*] coordinates {(marker-|0,0)};
                \else
                    \tikzset{options/.style={mark=none}}
                \fi
             \fi
        }{
            \tikzset{options/.style={mark=none}}        
        }
        \coordinate (marker) at (0,0);
        \begin{scope}[options]
    },
    scatter/@post marker code/.code={\end{scope}}
    }
}
\makeatother
% Defines a checkmark
\def\checkmark{\tikz\fill[scale=0.4,color=orange](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
\newcommand{\indep}{\perp \!\!\!\! \perp}
\setbeamertemplate{itemize items}{\checkmark}
\usepackage{multirow}
\hypersetup{pdfauthor={Bosancianu and Schaub},
	pdftitle={Statistical Modeling and Causal Inference with R},
	pdfsubject={Week 11: Causal Mediation},
	pdfkeywords={Berlin, Hertie, 2020, week 11, RDD}}
\title{\textsc{Statistical Modeling and Causal Inference with R}}
\subtitle{Week 11: Causal Mediation}
\date{November 23, 2020}
\author{Manuel Bosancianu \hfill Max Schaub}
\institute{Hertie School of Governance}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\maketitle



\begin{frame}
  \frametitle{Results: Baron--Kenny approach}
  


 \scriptsize
   \begin{align}
   Depression_i &= \alpha_1 + \beta_1\overbrace{Seminar_i}^{treatment} + \zeta_1X_i + \epsilon_{i1} \\
   Confidence_i &= \alpha_2 + \beta_2Seminar_i + \zeta_2X_i + \epsilon_{i2}\\
   Depression_i &= \alpha_3 + \gamma Seminar_i + \beta_3\underbrace{Confidence_i}_{mediator} + \zeta_3X_i + \epsilon_{i3}
   \end{align}





\begin{table}
\begin{center}
\begin{scriptsize}
\begin{tabular}{l D{.}{.}{4.6} D{.}{.}{4.6} D{.}{.}{4.6}}
\toprule
 & \multicolumn{1}{c}{DV: Depression} & \multicolumn{1}{c}{DV: Confidence} & \multicolumn{1}{c}{DV: Depression} \\
\midrule
(Intercept) & 0.895^{***} & 3.870^{***} & 1.499^{***}  \\
            & (0.133)     & (0.159)     & (0.158)      \\
Seminar     & -0.047      & 0.101^{*}   & -0.032       \\
            & (0.035)     & (0.042)     & (0.035)      \\
Confidence  &             &             & -0.156^{***} \\
            &             &             & (0.023)      \\
\bottomrule
\multicolumn{4}{p{8cm}}{\tiny{$^{***}p<0.001$; $^{**}p<0.01$; $^{*}p<0.05$. Estimates from pre-treatment covariates have been excluded from the table. $N=1285$. Measures of model fit removed from the table.}}
\end{tabular}
\end{scriptsize}
\label{tab:01}
\end{center}
\end{table}
  
\end{frame}


\begin{frame}
\frametitle{Computing effects \& uncertainty}

\begin{itemize}
\setlength\itemsep{1.5em}
  \item Direct effect: -0.032
  \item Indirect effect: $\beta_2\times \beta_3$ = $0.101\times -0.156$ = -0.016
  \item Total effect: $direct + indirect$ = $-0.032 + (-0.016)$ = $-0.047$ (rounding)
\end{itemize}
\pause

\begin{equation}
  SE_{indirect} = \sqrt{c^2\sigma_b^2 + b^2\sigma_c^2 + \sigma_b^2\sigma_c^2}
\end{equation}
\pause



\begin{table}
\scriptsize
\begin{tabular}{l D{.}{.}{4.6} D{.}{.}{4.6}}
\toprule
  & \multicolumn{1}{c}{Direct} & \multicolumn{1}{c}{Indirect} \\
\midrule
$\beta$ & -0.032 & -0.016^{*} \\
SE  &  (0.035) & (0.007) \\ 
\bottomrule
\end{tabular}
\end{table}

\end{frame}


\section{Causal mediation results}

\begin{frame}
  \frametitle{The Imai \textit{et al} setup I}
  \textit{Sequential ignorability} is still needed as fundamental assumption.\bigskip
  
  Requires only 2 regressions (OLS, logit, probit, survival\dots):
  
   \footnotesize
   \begin{align}
   Confidence_i &= \psi_1 + \phi_1\overbrace{Seminar_i}^{treatment} + \zeta_2X_i + \epsilon_{i2}\label{eq:01}\\
   Depression_i &= \psi_2 + \phi_2Seminar_i + \phi_3\underbrace{Confidence_i}_{mediator} + \zeta_3X_i + \epsilon_{i3} \label{eq:02}
   \end{align}
  \pause
  \normalsize
  
  Generate predictions for mediator from Equation \ref{eq:01}: $Confidence_i | Seminar_i=0$ and $Confidence_i | Seminar_i=1$.
\end{frame}


\begin{frame}
  \frametitle{The Imai \textit{et al} setup II}
  Generate predictions for the outcome from Equation \ref{eq:02}, using predictions for mediator: $Depression_i | Seminar_i=1, Confidence_i(1)$ and $Depression_i | Seminar_i=1, Confidence_i(0)$.
  
  \begin{equation}
    \footnotesize
		ACME = \delta_i(t) = Y_i(t, M_i(1)) - Y_i(t, M_i(0)),\; for\; each\; t\in \{0;1\}
	\end{equation}
  
  SEs computed with bootstrapping (or Monte Carlo methods).
  
\end{frame}


\begin{frame}[fragile]
  \frametitle{Syntax: Imai \textit{et al} approach}



\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# The "mediate()" function is used to calculate the }
\hlcom{# ACME and ADE}
\hlstd{med.out} \hlkwb{<-} \hlkwd{mediate}\hlstd{(}\hlkwc{model.m} \hlstd{= med.fit,}
                   \hlkwc{model.y} \hlstd{= out.fit,}
                   \hlkwc{sims} \hlstd{=} \hlnum{750}\hlstd{,}
                   \hlkwc{boot} \hlstd{=} \hlnum{TRUE}\hlstd{,}
                   \hlkwc{treat} \hlstd{=} \hlstr{"treat_num"}\hlstd{,}
                   \hlkwc{mediator} \hlstd{=} \hlstr{"job_seek"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

The automated function works with the two regression model objects.

\end{frame}


\begin{frame}[fragile]
  \frametitle{Results: Imai \textit{et al} approach}

\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

               Estimate 95% CI Lower 95% CI Upper p-value   
ACME            -0.0157      -0.0316         0.00  0.0053 **
ADE             -0.0316      -0.1006         0.04  0.3440   
Total Effect    -0.0473      -0.1198         0.02  0.1867   
Prop. Mediated   0.3327      -2.2380         2.76  0.1920   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1285 


Simulations: 750 
\end{verbatim}
\end{kframe}
\end{knitrout}

$ADE_{BK} = -0.032\; (0.035)$ and $ACME_{BK} = -0.016\; (0.007)$.

\end{frame}


\begin{frame}
  \frametitle{Sensitivity analysis I}
  ACME unbiased if $cov(\epsilon_{i2}, \epsilon_{i3})=0$ (call this $\rho$).\bigskip
  
  If \textit{sequential ignorability} holds, then $\rho=0$. If not, estimates are biased.\bigskip
  \pause
  
  In practice, sensitivity analysis is based on a function of $R^2$ from the two models \cite<see>[pp. 61--62]{imai_identification_2010}.

\end{frame}


\begin{frame}[fragile]
  \frametitle{Sensitivity analysis II}
  
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# "medsens()" is the function which conducts the}
\hlcom{# sensitivity analysis}
\hlstd{sens.out} \hlkwb{<-} \hlkwd{medsens}\hlstd{(med.out,}
                    \hlkwc{rho.by} \hlstd{=} \hlnum{0.05}\hlstd{,}
                    \hlkwc{sims} \hlstd{=} \hlnum{750}\hlstd{,}
                    \hlkwc{effect.type} \hlstd{=} \hlstr{"indirect"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

Mediation Sensitivity Analysis for Average Causal Mediation Effect

Sensitivity Region

       Rho    ACME 95% CI Lower 95% CI Upper R^2_M*R^2_Y* R^2_M~R^2_Y~
[1,] -0.25  0.0056      -0.0008       0.0121       0.0625       0.0403
[2,] -0.20  0.0012      -0.0035       0.0058       0.0400       0.0258
[3,] -0.15 -0.0032      -0.0084       0.0020       0.0225       0.0145
[4,] -0.10 -0.0074      -0.0150       0.0001       0.0100       0.0064

Rho at which ACME = 0: -0.2
R^2_M*R^2_Y* at which ACME = 0: 0.04
R^2_M~R^2_Y~ at which ACME = 0: 0.0258 
\end{verbatim}
\end{kframe}
\end{knitrout}

\end{frame}

\begin{frame}[fragile]
  \frametitle{Sensitivity analysis III}
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{figure/r_imai-al-sensitivity-3-1} 

}


\end{knitrout}
  
\end{frame}


% END
\begin{frame}
\begin{center}
    \Huge Thank \textcolor{orange}{you} for the kind attention!
\end{center}
\end{frame}

% REFERENCES %

\begin{frame}[allowframebreaks, plain]
\bibliographystyle{apacite}
\scriptsize\bibliography{../Bibliography}
\end{frame}

\end{document}
